export SRC_PROD_USER=MYANG
export SRC_PROD_ACCOUNT=snowflake.va.us-east-1.external-zone
export SRC_PROD_ROLE=ENG_OPS_RL
export SRC_PROD_DATABASE=SCRATCH
export SRC_PROD_SCHEMA=MIGRATION
export SRC_PROD_WAREHOUSE=SUPPORT_2XL
export SOURCE_ACCOUNT=MIGRATION

export SRC_CUST_USER=MYANG
export SRC_CUST_ACCOUNT=migration.us-east-1
export SRC_CUST_PWD=xxx
export SRC_CUST_ROLE=REPADMIN
export SRC_CUST_DATABASE=DB_CROSSREP
export SRC_CUST_SCHEMA=SC_CROSSREP
export SRC_CUST_WAREHOUSE=WH_CROSSREP

export TGT_CUST_USER=MYANG
export TGT_CUST_ACCOUNT=migration
export TGT_CUST_PWD=xxx
export TGT_CUST_ROLE=REPADMIN
export TGT_CUST_DATABASE=DB_CROSSREP
export TGT_CUST_SCHEMA=SC_CROSSREP
export TGT_CUST_WAREHOUSE=WH_CROSSREP

export TARGET_ROLE=REPADMIN
export MIGRATION_HOME=/Users/myang/crossrep/
export REP_MODE=CUSTOMER
export AU_DATABASE=DB_CROSSREP
export AU_SCHEMA=SC_ACCTUSAGE
export REP_ACCT_LIST=aws_us_west_2.migration
export FAILOVER_ACCT_LIST=aws_us_west_2.migration

export SNOWHOUSE_USER=MYANG
export SNOWHOUSE_ACCOUNT=SNOWHOUSE 
export SNOWHOUSE_ROLE=SNOWHOUSE_PHI_RO_RL
export SNOWHOUSE_DATABASE=SNOWHOUSE_IMPORT
export SNOWHOUSE_SCHEMA=VA 
export SNOWHOUSE_WAREHOUSE=SNOWHOUSE 
export SNOWHOUSE_DEPLOYMENT=VA
export SNOWHOUSE_CUST_ACCOUNT=MYACCOUNT  
